# Generated by Django 3.0.6 on 2020-12-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratingapp', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieratingapp.Images'),
        ),
    ]
